### ISSUE TITLE
Change `FusionRenderingService` return value restriction

### ISSUE THREAD

**Issue by jobee** [punktDe/outofbandrendering#1]
Hey @daniellienert ,
was there a reason why you restricted the return values of `render` and `renderByIdentifier` to `string` ?
Wouldn't it be much more flexible if we could render e.g. `Neos.Fusion:RawArray` s like:

```
searchSuggestionPayload = Neos.Fusion:RawArray {
  label = ${node.label}
  href = NodeUri {
    node = ${documentNode}
  }
  thumbnail  = ImageUri {
    @if.hasImage = ${node.properties.image}
    asset = ${node.properties.image}
    width = 53
    height = 53
    allowCropping = true
    allowUpScaling = true
  }
}
```

**Comment by daniellienert** [comment]
Hey @jobee, sorry for not responding for 2 years. 
I see your point, constraints are removed.
